version: "3.8"

services:
  budgets:
    image: ghcr.io/slopessierra/budgets:latest
    ports:
      - "6622:3000"
      - "3001:3001"
    env_file:
      - .env
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true
    tty: true